### ISSUE TITLE
geef * nog een padding 0 margin 0

### ISSUE THREAD

**Issue by Jesse-L3** [TristanKatte/connect-your-tribe-profile-card#3]
Dit maakt het vervolgens makkelijker wanneer je andere elementen padding en margin geeft

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```
